# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: '2'

services:
  todo-postgres:
    image: {{ .Values.todoImageUser }}/todo-postgres:{{ .Values.todoVersion }}

  todo-cache-ingestion:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-cache-ingestion:{{ .Values.todoVersion }}

  todo-cache-service:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-cache-service:{{ .Values.todoVersion }}

  todo-search-ingestion:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-search-ingestion:{{ .Values.todoVersion }}
    command: sh /home/node/app/start.sh

  todo-search-service:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-search-service:{{ .Values.todoVersion }}
    command: sh /home/node/app/start.sh

  todo-storage-ingestion:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-storage-ingestion:{{ .Values.todoVersion }}
    command: sh /home/node/app/start.sh

  todo-storage-service:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-storage-service:{{ .Values.todoVersion }}

  todo-api-gateway:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: {{ .Values.todoImageUser }}/todo-api-gateway:{{ .Values.todoVersion }}
    command: sh /home/node/app/start.sh

  todo-view:
    build:
      dockerfile: Dockerfile.prod
    image: {{ .Values.todoImageUser }}/todo-view:{{ .Values.todoVersion }}
    ports:
      - 4201:8080

  todo-proxy:
    image: {{ .Values.todoImageUser }}/todo-proxy:{{ .Values.todoVersion }}
